<?php
eBConDb::eBgetInstance()->eBgetConection()->query("INSERT INTO `blog_category` (`contents_category_id`, `contents_category`) VALUES
(1, 'WordPress'),
(2, 'Website-Template'),
(3, 'UI-UX'),
(4, 'Graphics-Design'),
(5, 'Print-Design'),
(6, 'Web-Graphics'),
(7, 'Photoshop-Tutorial'),
(8, 'Photo-Editing'),
(9, 'Video-Editing'),
(10, 'Submit-your-Article'),
(11, 'Hobby'),
(12, 'SEO'),
(13, 'PHP'),
(14, 'SQL'),
(15, 'Sales-Leads')");

eBConDb::eBgetInstance()->eBgetConection()->query("INSERT INTO `blog_sub_category` (`contents_sub_category_id`, `contents_sub_category`, `contents_category_in_blog_sub_category`) VALUES
(1, 'Blog-Magazine', 'WordPress'),
(2, 'Education', 'WordPress'),
(3, 'Entertainment', 'WordPress'),
(4, 'WooCommerce', 'WordPress'),
(5, 'Events-Booking', 'WordPress'),
(6, 'Rental-Website', 'WordPress'),
(7, 'Admin-Templates', 'Website-Template'),
(8, 'Landing-Pages', 'Website-Template'),
(9, 'Contact-Pages', 'Website-Template'),
(10, '404-Pages', 'Website-Template'),
(11, 'Search-Pages', 'Website-Template'),
(12, 'IOS-PSD-Templates', 'UI-UX'),
(13, 'Android-PSD-Template', 'UI-UX'),
(14, 'Responsive-Web-Design', 'UI-UX'),
(15, 'Background-Images', 'Graphics-Design'),
(16, 'Hero-Image', 'Graphics-Design'),
(17, 'Product-Mockup-Templates', 'Graphics-Design'),
(18, 'Brochure-Templates', 'Print-Design'),
(19, 'Business-Card-Templates', 'Print-Design'),
(20, 'Magazine-Templates', 'Print-Design'),
(21, 'Packaging-Templates', 'Print-Design'),
(22, 'Product-PSD-Mockup', 'Web-Graphics'),
(23, 'Banner-ADs', 'Web-Graphics'),
(24, 'PSD-Templates', 'Photoshop-Tutorial'),
(25, 'Clipping-path', 'Photo-Editing'),
(26, 'Color-correction', 'Photo-Editing'),
(27, 'Image-manipulation', 'Photo-Editing'),
(28, 'Image-masking', 'Photo-Editing'),
(29, 'Manequin-ghost', 'Photo-Editing'),
(30, 'Multi-clipping-path', 'Photo-Editing'),
(31, 'Neck-joint', 'Photo-Editing'),
(32, 'Photo-retouch', 'Photo-Editing'),
(33, 'Shadow', 'Photo-Editing'),
(34, 'Video-Editing-Templates', 'Video-Editing'),
(35, 'Guest-Post', 'Submit-your-Article'),
(36, 'Fashion-Design', 'Hobby'),
(37, 'Gardening', 'Hobby'),
(38, 'Cooking', 'Hobby'),
(39, 'Travelling', 'Hobby'),
(40, 'Crochet', 'Hobby'),
(41, 'Cultivate', 'Hobby'),
(42, 'Science-and-Technology', 'Hobby'),
(43, 'Photography', 'Hobby'),
(44, 'Painting', 'Hobby'),
(45, 'Exercise', 'Hobby'),
(46, 'Dance', 'Hobby'),
(47, 'Scrapbooking', 'Hobby'),
(48, 'Video-Games', 'Hobby'),
(49, 'Chess', 'Hobby'),
(50, 'Pottery', 'Hobby'),
(51, 'Archery', 'Hobby'),
(52, 'Cycling', 'Hobby'),
(53, 'Scuba-Diving', 'Hobby'),
(54, 'Baking', 'Hobby'),
(55, 'Toys', 'Hobby'),
(56, 'Embroidery', 'Hobby'),
(57, 'Calligraphy', 'Hobby'),
(58, 'Guitars', 'Hobby'),
(59, 'Football', 'Hobby'),
(60, 'Underwater-Diving', 'Hobby'),
(61, 'Football', 'Hobby'),
(62, 'Quilting', 'Hobby'),
(63, 'Parachuting', 'Hobby'),
(64, 'Singing', 'Hobby'),
(65, 'Organic-Visitor', 'SEO'),
(66, 'CMS', 'PHP'),
(67, 'Blog', 'PHP'),
(68, 'Portfolio-Website', 'PHP'),
(69, 'eCommerce-Website', 'PHP'),
(70, 'Booking-System', 'PHP'),
(71, 'Generate-Sales-Leads', 'Sales-Leads'),
(72, 'Keyword-Targeted', 'Sales-Leads')");

?>